config/routes.rb
Rails.application.routes.draw do

  resources :public, :only => [:index, :show]

  resources :users do
    member do
      get :delete
    end
  end

  resources :memes do
    member do
      get :delete
    end
  end

  resources :images do
    member do
      get :delete
    end
  end

  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  has_attached_file :upload, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :upload, content_type: /\Aimage\/.*\z/

  belongs_to :user

  scope :recent, lambda {order("created_at ASC")}
end

app/models/meme.rb
class Meme < ApplicationRecord

  # has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  # validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  belongs_to :user

  validates :name,           :presence => true
  validates :text,           :presence => true

  scope :recent, lambda {order("created_at ASC")}

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :memes
  has_many :images

  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

  validates :first_name,  :presence => true
  validates :last_name,   :presence => true
  validates :username,    :presence => true,
                          :uniqueness => true
  validates :email,       :presence => true,
                          :uniqueness => true,
                          :format => EMAIL_REGEX

  scope :sorted, lambda {order("username ASC")}

  def name
    "#{first_name} #{last_name}"
  end

end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  def login
    # login form /views/access/login
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = User.where(:username => params[:username]).first
      # could use an else to put a message into flash for "please input username and password."
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end

    if authorized_user
      session[:user_id] = authorized_user.id
      session[:username] = authorized_user.username
      flash[:notice] = "You are now logged in."
      redirect_to(users_path)
    else
      flash.now[:notice] = "Invalid username/password combination."
      render('login')
    end

  end

  def logout
    session[:user_id] = nil
    session[:username] = nil
    flash[:notice] = 'Logged out.'
    redirect_to(access_login_path)
  end

  private

  def confirm_logged_in
    unless session[:user_id]
      flash[:notice] = "Please log in."
      redirect_to(access_login_path)
    end
  end

  # @current_user ||= User.find(session[:user_id])

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

end

app/controllers/image_controller.rb
class ImageController < AccessController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def delete
  end
end

app/controllers/images_controller.rb
class ImagesController < AccessController

  def index
    @images = Image.recent
  end

  def show
    @image = Image.find(params[:id])
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    @image.user_id = session[:user_id]
    if @image.save
      flash[:notice] = "You saved a new image! Great work."
      redirect_to(images_path)
    else
      render('new')
    end
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update

  end

  def delete
    @image = Image.find(params[:id])
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to(images_path)
  end

  private

  def image_params
    params.require(:image).permit(:upload, :name)
  end
end

app/controllers/memes_controller.rb
class MemesController < AccessController

  before_action :confirm_logged_in

  def index
    @memes = Meme.recent
  end

  def show

  end

  def new
    @meme = Meme.new
  end

  def create
    @meme = Meme.new(meme_params)
    @meme.user_id = session[:user_id]
    if @meme.save
      flash[:notice] = "You just created a new meme!"
      redirect_to(memes_path)
    else
      render('new')
    end
  end

  def edit
    @meme = Meme.find(params[:id])
  end

  def update
    @meme = Meme.find(params[:id])
    if @meme.update_attributes(meme_params)
      flash[:notice] = "You updated your meme!"
      redirect_to(memes_path)
    else
      render('edit')
    end
  end

  def delete
    @meme = Meme.find(params[:id])
  end

  def destroy
    @meme = Meme.find(params[:id])
    @meme.destroy
    redirect_to(memes_path)
  end

  private

  def meme_params
    params.require(:meme).permit(:name, :text)
  end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController

  def index

  end

  def show
    
  end

end

app/controllers/users_controller.rb
class UsersController < AccessController

  before_action :confirm_logged_in

  def index
    @users = User.sorted
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "The user #{@user.name} was created successfully."
      redirect_to(users_path)
    else
      render('new')
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = "The user was updated successfully."
      redirect_to(users_path)
    else
      render('edit')
    end
  end

  def delete
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to(users_path)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password)
  end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/memes_helper.rb
module MemesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/access/login.html.erb
<% @page_title = "User Login" %>

<div class="login">
  <%= form_tag(access_attempt_login_path, :method => :post) do %>
  <table>
    <tr>
      <td><%= label_tag(:username) %></td>
      <td><%= text_field_tag(:username, params[:username]) %></td>
    </tr>
    <tr>
      <td><%= label_tag(:password) %></td>
      <td><%= password_field_tag(:password) %></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><%= submit_tag("Log In") %></td>
    </tr>
  </table>
  <% end %>
</div>

app/views/images/_form.html.erb
<table summary="Image form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Image</th>
    <td><%= f.file_field(:upload) %></td>
  </tr>
</table>

app/views/images/delete.html.erb
<%= link_to("<< Back to List", images_path, :class => 'back-link') %>

<div class="images delete">
  <h2>Delete Image</h2>

  <%= form_for(@image, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this image?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Image") %>
    </div>

  <% end %>
</div>
<%= link_to("Logout", access_logout_path) %>

app/views/images/edit.html.erb
<h1>Image#edit</h1>
<p>Find me in app/views/image/edit.html.erb</p>

app/views/images/index.html.erb
<% @page_title = "Your Images" %>
<div class="images index">
  <h2>Images</h2>
  <%= image_tag('plus_sign.png', :size => '11x11', :alt => '+') %>
  <%= link_to("Add New Image", new_image_path, :class => 'action new') %>

  <div><%= pluralize(@images.size, 'image') %> found</div>

  <table class="listing" summary="Images list">
    <tr class="header">
      <th>Name</th>
      <th>Filename</th>
      <th>Preview</th>
      <th>Actions</th>
    </tr>
    <% @images.recent.each do |image| %>
    <tr>
      <td><%= image.name %></td>
      <td><%= image.upload_file_name %></td>
      <td><%= image_tag image.upload.url(:thumb) %></td>
      <td class="actions">
        <%= link_to("Show", image_path(image), :class => 'action show') %>
        <%= link_to("Edit", edit_image_path(image), :class => 'action edit') %>
        <%= link_to("Delete", delete_image_path(image), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/images/new.html.erb
<%= link_to("<< Back to List", images_path, :class => 'back-link') %>

<div class="images new">
  <h2>Add an Image</h2>

  <%= form_for(@image, :url => images_path, :method => 'post') do |f| %>

  <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Upload Image") %>
    </div>

  <% end %>
</div>
<%= link_to("Logout", access_logout_path) %>

app/views/images/show.html.erb
<h1>Image#show</h1>
<p>Find me in app/views/image/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Memeory</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/memes/_form.html.erb
<table summary="Meme form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Text</th>
    <td><%= f.text_field(:text) %></td>
  </tr>
</table>

app/views/memes/delete.html.erb
<%= link_to("<< Back to List", memes_path, :class => 'back-link') %>

<div class="memes delete">
  <h2>Delete Meme</h2>

  <%= form_for(@meme, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this meme?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Meme") %>
    </div>

  <% end %>
</div>
<%= link_to("Logout", access_logout_path) %>

app/views/memes/edit.html.erb
<%= link_to("<< Back to List", memes_path, :class => 'back-link') %>

<div class="memes edit">
  <h2>Edit Meme</h2>

  <%= form_for(@meme) do |f| %>

  <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Meme") %>
    </div>

  <% end %>
</div>
<%= link_to("Logout", access_logout_path) %>

app/views/memes/index.html.erb
<% @page_title = "Your Memes" %>
<div class="memes index">
  <h2>Memes</h2>
  <%= image_tag('plus_sign.png', :size => '11x11', :alt => '+') %>
  <%= link_to("Add New Meme", new_meme_path, :class => 'action new') %>

  <div><%= pluralize(@memes.size, 'meme') %> found</div>

  <table class="listing" summary="Memes list">
    <tr class="header">
      <th>Name</th>
      <th>Text</th>
      <th>Actions</th>
    </tr>
    <% @memes.recent.each do |meme| %>
    <tr>
      <td><%= meme.name %></td>
      <td><%= meme.text %></td>
      <td class="actions">
        <%= link_to("Show", meme_path(meme), :class => 'action show') %>
        <%= link_to("Edit", edit_meme_path(meme), :class => 'action edit') %>
        <%= link_to("Delete", delete_meme_path(meme), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/memes/new.html.erb
<%= link_to("<< Back to List", memes_path, :class => 'back-link') %>

<div class="memes new">
  <h2>Add a Meme</h2>

  <%= form_for(@meme, :url => memes_path, :method => 'post') do |f| %>

  <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Save Meme") %>
    </div>

  <% end %>
</div>
<%= link_to("Logout", access_logout_path) %>

app/views/memes/show.html.erb
<h1>Meme#show</h1>
<p>Find me in app/views/meme/show.html.erb</p>

app/views/users/_form.html.erb
<table summary="User form fields">
  <tr>
    <th>First Name</th>
    <td><%= f.text_field(:first_name) %></td>
  </tr>
  <tr>
    <th>Last Name</th>
    <td><%= f.text_field(:last_name) %></td>
  </tr>
  <tr>
    <th>Username</th>
    <td><%= f.text_field(:username) %></td>
  </tr>
  <tr>
    <th>Email</th>
    <td><%= f.text_field(:email) %></td>
  </tr>
  <tr>
    <th>Password</th>
    <td><%= f.password_field(:password) %></td>
  </tr>
</table>

app/views/users/delete.html.erb
<%= link_to("<< Back to List", users_path, :class => 'back-link') %>

<div class="users delete">
  <h2>Delete User</h2>

  <%= form_for(@user, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this user?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete User") %>
    </div>

  <% end %>
</div>

app/views/users/edit.html.erb
<%= link_to("<< Back to List", users_path, :class => 'back-link') %>

<div class="users edit">
  <h2>Edit User</h2>

  <%= form_for(@user) do |f| %>

  <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update User") %>
    </div>

  <% end %>
</div>
<%= link_to("Logout", access_logout_path) %>

app/views/users/index.html.erb
<% @page_title = "All Users" %>
<div class="users index">
  <h2>Users</h2>
  <%= image_tag('plus_sign.png', :size => '11x11', :alt => '+') %>
  <%= link_to("Add New User", new_user_path, :class => 'action new') %>

  <div><%= pluralize(@users.size, 'user') %> found</div>

  <table class="listing" summary="Users list">
    <tr class="header">
      <th>Name</th>
      <th>Username</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
    <% @users.sorted.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.username %></td>
      <td><%= mail_to(user.email) %></td>
      <td class="actions">
        <%= link_to("Show", user_path(user), :class => 'action show') %>
        <%= link_to("Edit", edit_user_path(user), :class => 'action edit') %>
        <%= link_to("Delete", delete_user_path(user), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>
<%= link_to("Logout", access_logout_path) %>

app/views/users/new.html.erb
<%= link_to("<< Back to List", users_path, :class => 'back-link') %>

<div class="users new">
  <h2>Create User</h2>

  <%= form_for(@user, :url => users_path, :method => 'post') do |f| %>

  <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create User") %>
    </div>

  <% end %>
</div>
<%= link_to("Logout", access_logout_path) %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<%= link_to("Logout", access_logout_path) %>